language: python

env:
  global:
    - TWINE_USERNAME=randy3k

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic
      before_install:
        - python -m pip install virtualenv
        - python -m virtualenv venv
        - source venv/bin/activate

script:
  - python -m pip install cibuildwheel==0.10.1
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi
