language: python

sudo: required

python:
  - 2.7
  - 3.5

env:
  - RVERSION="3.4.1"
  - RVERSION="3.4.2"
  - RVERSION="3.4.3"
  - RVERSION="3.4.4"
  - RVERSION="release"

before_install:
  - sh travis.sh install-r "$RVERSION"
  - pip install .

script:
  - pytest -s


deploy:
  provider: pypi
  user: randy3k
  password:
    secure: p0WkLNnA2UGBL9u/r+UixTNHJFSjWGe3pdClVHd/OPR7hi3qD5WQEKcbdkFWnrH+Z91mf7+yXBhUMG6l+3wnxCOqZSpCkwEhG0gAOoRL/+ZVVXx+xtSvs6IZ0kNi2vul2zCMTWOdpWKiQOwbyn6BnhRfaKIUYprbic7p4ZCubpf/pufOoAnJTh1Djs4lKvssTAVCE/Hg/6i64nX5koIBwVhYyTKDfOBrAHNiDR5xgHzmf+QCe6Md/Ly3u6KOpcdRc0Ew7Hf9WzVls9XvzG+eqWuvuYmZeDOE5dgBwEWTYs/SSlSkmZzFPFfo9IbmVDaZVW7euHeIenUmyPUn9ztuK8KTn78rWnsrxbf3rIY+/xaO98FfC4aL1QoX0+hrQV4EmkTOjF5q62ZzXWMeghWqxBLF3GL9DcPI0igHkftLdzdNDecMLlr8Y/qe2sW9iUs86/4lUXfmzmS5GTF1Q/FpP73Izy9IwwBWwbvApgA5GStAZIAncLL9SyCNyoU1qcpYDPkHSp6dzP1oXuE39cP6hvjY4lhHtuthnU7JdWu3ZDHLVULKlJQiMBcKlkE9668DSfkbI9y42Xn0jFEVVtGY8enED//CxKM7RIC3L3mnoEz3HJBqf/3z1iVM7QoGbjbdqH/vMLbod1ywryfR3/jPUS8G3oBm8ZkuuG0fLoHUDEw=
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: change
