environment:
  USE_RTOOLS: true
  matrix:
    - PYTHON: "C:\\Python27-x64"
      R_VERSION: "3.5.3"

    - PYTHON: "C:\\Python37-x64"
      R_VERSION: "3.5.3"

    - PYTHON: "C:\\Python27-x64"
      R_VERSION: "release"

    - PYTHON: "C:\\Python37-x64"
      R_VERSION: "release"

    - PYTHON: "C:\\Python27-x64"
      R_VERSION: "devel"

    - PYTHON: "C:\\Python37-x64"
      R_VERSION: "devel"

    - BUILD_WHEEL: true

# matrix:
#   allow_failures:
#     - R_VERSION: "devel"

for:
  -
    matrix:
      except:
        - BUILD_WHEEL: true
    init:
      - ECHO %PYTHON%
      # https://github.com/rstudio/reticulate/blob/master/appveyor.yml
      - ps: |
            $ErrorActionPreference = "Stop"
            Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
            Import-Module '..\appveyor-tool.ps1'
    install:
      - ps: Bootstrap
      - R -e "install.packages('reticulate', repo = '"https://cloud.r-project.org"')"
      - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
      - python -m pip install --upgrade setuptools pip
      - python -m pip install -e .[test]
    build_script:
      - pytest -s --cov=rchitect
    after_build:
      - python -m pip install codecov
      - codecov
    # on_failure:
    #   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  -
    matrix:
      only:
        - BUILD_WHEEL: true
    install:
      - python -m pip install cibuildwheel==0.10.1
      - cibuildwheel --output-dir wheelhouse
    build_script:
      - >
        IF "%APPVEYOR_REPO_TAG%" == "true" (
          python -m pip install twine
          &&
          python -m twine upload wheelhouse/*.whl
        )

    artifacts:
      - path: "wheelhouse\\*.whl"
        name: Wheels
