version: 2

jobs:
  test-r-3.4.4:
    docker:
      - image: rocker/tidyverse:3.4.4
    steps:
      - run: |
          apt-get update
          apt-get install git ssh curl python3 python3-pip libffi6 libffi-dev -y
      - run: R --slave -e "devtools::install_github('rstudio/reticulate#279')"
      - checkout
      - run: pip3 install -e .[test]
      - run: |
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
          pytest
  test-r-release:
    docker:
      - image: rocker/tidyverse
    steps:
      - run: |
          apt-get update
          apt-get install git ssh curl python3 python3-pip libffi6 libffi-dev -y
      - run: R --slave -e "devtools::install_github('rstudio/reticulate#279')"
      - checkout
      - run: pip3 install -e .[test]
      - run: |
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
          pytest
  test-r-devel:
    docker:
      - image: rocker/tidyverse:devel
    steps:
      - run: |
          apt-get update
          apt-get install git ssh curl python3 python3-pip libffi6 libffi-dev -y
      - run: R --slave -e "devtools::install_github('rstudio/reticulate#279')"
      - checkout
      - run: pip3 install -e .[test]
      - run: |
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
          pytest
  deploy-to-pypi:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo pip install twine
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = randy3k" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run: |
          python setup.py sdist
          twine upload dist/*
workflows:
  version: 2
  build:
    jobs:
      - test-r-3.4.4:
          filters:
            tags:
              only: /^v.*/
      - test-r-release:
          filters:
            tags:
              only: /^v.*/
      - test-r-devel:
          filters:
            tags:
              only: /^v.*/
      - deploy-to-pypi:
          requires:
            - test-r-3.4.4
            - test-r-release
            - test-r-devel
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
