version: 2.1

commands:
  install-deps:
    steps:
      - run: |
          apt-get update
          apt-get install git ssh curl bzip2 libffi6 libffi-dev -y
      - checkout
  install-python:
    parameters:
      tag:
        type: string
        default: "3.6"
    steps:
      - run: |
          curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
          bash /tmp/miniconda.sh -b -f -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          conda create --name myenv python=<<parameters.tag>>
  run-tests:
    steps:
      - run: R --slave -e "install.packages('reticulate', repo = 'https://cloud.r-project.org')"
      - run: |
          export PATH="$HOME/miniconda/bin:$PATH"
          source activate myenv
          python -m pip install -e .[test]
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
          pytest -s --cov=rchitect
          python -m pip install codecov
          codecov

executors:
  rocker:
    parameters:
      tag:
        type: string
        default: latest
    docker:
      - image: rocker/tidyverse:<< parameters.tag >>

jobs:
  test-r-latest-py27:
    executor:
      name: rocker
      tag: latest
    steps:
      - install-deps
      - install-python:
          tag: "2.7"
      - run-tests
  test-r-latest-py35:
    executor:
      name: rocker
      tag: latest
    steps:
      - install-deps
      - install-python:
          tag: "3.5"
      - run-tests
  test-r-latest-py36:
    executor:
      name: rocker
      tag: latest
    steps:
      - install-deps
      - install-python:
          tag: "3.6"
      - run-tests
  test-r-latest-py37:
    executor:
      name: rocker
      tag: latest
    steps:
      - install-deps
      - install-python:
          tag: "3.7"
      - run-tests
  test-r-devel-py27:
    executor:
      name: rocker
      tag: devel
    steps:
      - install-deps
      - install-python:
          tag: "2.7"
      - run-tests
  test-r-devel-py37:
    executor:
      name: rocker
      tag: devel
    steps:
      - install-deps
      - install-python:
          tag: "3.7"
      - run-tests
  test-r-35-py27:
    executor:
      name: rocker
      tag: "3.5"
    steps:
      - install-deps
      - install-python:
          tag: "2.7"
      - run-tests
  test-r-35-py37:
    executor:
      name: rocker
      tag: "3.5"
    steps:
      - install-deps
      - install-python:
          tag: "3.7"
      - run-tests

  linux-wheels:
    working_directory: /tmp/workspace
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Linux wheels.
          command: |
            sudo python -m pip install cibuildwheel
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - wheelhouse
  osx-wheels:
    working_directory: /tmp/workspace
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Build the OS X wheels.
          command: |
            python -m pip install cibuildwheel
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - wheelhouse
  upload-tarball:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo python -m pip install twine
      - run: |
          python setup.py sdist
          twine upload dist/*
  upload-wheels:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: sudo python -m pip install twine
      - run: twine upload /tmp/workspace/wheelhouse/*.whl

workflows:
  version: 2
  build:
    jobs:
      - test-r-latest-py27:
          filters:
            tags:
              only: /^v.*/
      - test-r-latest-py35:
          filters:
            tags:
              only: /^v.*/
      - test-r-latest-py36:
          filters:
            tags:
              only: /^v.*/
      - test-r-latest-py37:
          filters:
            tags:
              only: /^v.*/
      - test-r-devel-py27:
          filters:
            tags:
              only: /^v.*/
      - test-r-devel-py37:
          filters:
            tags:
              only: /^v.*/
      - test-r-35-py27:
          filters:
            tags:
              only: /^v.*/
      - test-r-35-py37:
          filters:
            tags:
              only: /^v.*/
      - linux-wheels:
          filters:
            tags:
              only: /^v.*/
      - osx-wheels:
          filters:
            tags:
              only: /^v.*/
      - upload-tarball:
          requires:
            - test-r-latest-py27
            - test-r-latest-py35
            - test-r-latest-py36
            - test-r-latest-py37
            - test-r-devel-py27
            - test-r-devel-py37
            - test-r-35-py27
            - test-r-35-py37
            - linux-wheels
            - osx-wheels
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - upload-wheels:
          requires:
            - test-r-latest-py27
            - test-r-latest-py35
            - test-r-latest-py36
            - test-r-latest-py37
            - test-r-devel-py27
            - test-r-devel-py37
            - test-r-35-py27
            - test-r-35-py37
            - linux-wheels
            - osx-wheels
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
