version: 2

jobs:
  test-r-3.4.4-py2:
    docker:
      - image: rocker/r-ver:3.4.4
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install git curl python python-pip -y
          pip install pytest
      - run: pip install -e .
      - run: pytest
  test-r-release-py2:
    docker:
      - image: rocker/r-base
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install git curl python python-pip -y
          pip install pytest
      - run: pip install -e .
      - run: pytest
  test-r-devel-py2:
    docker:
      - image: rocker/r-ver:devel
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install git curl python python-pip -y
          pip install pytest
      - run: pip install -e .
      - run: pytest
  test-r-3.4.4-py3:
    docker:
      - image: rocker/r-ver:3.4.4
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install git curl python3 python3-pip -y
          pip3 install pytest
      - run: pip3 install -e .
      - run: pytest
  test-r-release-py3:
    docker:
      - image: rocker/r-base
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install git curl python3 python3-pip -y
          pip3 install pytest
      - run: pip3 install -e .
      - run: pytest
  test-r-devel-py3:
    docker:
      - image: rocker/r-ver:devel
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install git curl python3 python3-pip -y
          pip3 install pytest
      - run: pip3 install -e .
      - run: pytest


workflows:
  version: 2
  build_and_test:
    jobs:
      - test-r-3.4.4-py2
      - test-r-release-py2
      - test-r-devel-py2
      - test-r-3.4.4-py3
      - test-r-release-py3
      - test-r-devel-py3
