version: 2.1

commands:
  install-deps:
    steps:
      - run: |
          apt-get update
          apt-get install git ssh curl bzip2 libffi6 libffi-dev -y
  install-python:
    parameters:
      tag:
        type: string
        default: "3.6"
    steps:
      - run: |
          curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
          bash /tmp/miniconda.sh -b -f -p $HOME/miniconda
          $HOME/miniconda/bin/conda create --name myenv python=<<parameters.tag>>
  run-tests:
    steps:
      - run: R --slave -e "install.packages('reticulate', repo = 'https://cloud.r-project.org')"
      - run: |
          source $HOME/miniconda/bin/activate myenv
          python -m pip install -e .[test]
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
          pytest -s --cov=rchitect
          python -m pip install codecov
          codecov

executors:
  rocker:
    parameters:
      tag:
        type: string
        default: latest
    docker:
      - image: rocker/tidyverse:<< parameters.tag >>

jobs:
  pytest:
    parameters:
      r:
        type: string
      python:
        type: string
    executor:
      name: rocker
      tag: <<parameters.r>>
    steps:
      - install-deps
      - checkout
      - install-python:
          tag: <<parameters.python>>
      - run-tests
  linux-wheels:
    working_directory: /tmp/workspace
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Linux wheels.
          command: |
            sudo python -m pip install cibuildwheel
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - wheelhouse
  osx-wheels:
    working_directory: /tmp/workspace
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Build the OS X wheels.
          command: |
            python -m pip install cibuildwheel
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - wheelhouse
  upload-tarball:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo python -m pip install twine
      - run: |
          python setup.py sdist
          twine upload dist/*
  upload-wheels:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: sudo python -m pip install twine
      - run: twine upload /tmp/workspace/wheelhouse/*.whl

workflows:
  version: 2
  build:
    jobs:
      - pytest:
          name: rlatest-py27
          r: latest
          python: "2.7"
          filters:
            tags:
              only: /^v.*/
      - pytest:
          name: rlatest-py34
          r: latest
          python: "3.4"
          filters:
            tags:
              only: /^v.*/
      - pytest:
          name: rlatest-py35
          r: latest
          python: "3.5"
          filters:
            tags:
              only: /^v.*/
      - pytest:
          name: rlatest-py36
          r: latest
          python: "3.6"
          filters:
            tags:
              only: /^v.*/
      - pytest:
          name: rlatest-py37
          r: latest
          python: "3.7"
          filters:
            tags:
              only: /^v.*/
      - pytest:
          name: rdevel-py27
          r: devel
          python: "2.7"
          filters:
            tags:
              only: /^v.*/
      - pytest:
          name: rdevel-py37
          r: devel
          python: "3.7"
          filters:
            tags:
              only: /^v.*/
      - pytest:
          name: r35-py27
          r: "3.5"
          python: "2.7"
          filters:
            tags:
              only: /^v.*/
      - pytest:
          name: r35-py37
          r: "3.5"
          python: "3.7"
          filters:
            tags:
              only: /^v.*/
      - linux-wheels:
          filters:
            tags:
              only: /^v.*/
      - osx-wheels:
          filters:
            tags:
              only: /^v.*/
      - upload-tarball:
          requires:
            - rlatest-py27
            - rlatest-py34
            - rlatest-py35
            - rlatest-py36
            - rlatest-py37
            - rdevel-py27
            - rdevel-py37
            - r35-py27
            - r35-py37
            - linux-wheels
            - osx-wheels
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - upload-wheels:
          requires:
            - upload-tarball
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
