name: Test radian

on: [push, pull_request]

env:
  RADIAN_NO_INPUTHOOK: 1

jobs:
  pytest:
    name: Running radian tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        r: [latest]
        # r: [3.5, latest, devel]
        python: [3.7]
        # python: [2.7, 3.5, 3.6, 3.7]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: ${{ matrix.python }}
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r }}
      - name: Install reticulate
        run: Rscript -e "install.packages('reticulate')"
      - name: Insert LD_LIBRARY_PATH
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: echo LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib" >> $GITHUB_ENV
      - name: Install and run tests
        run: |
          python -m pip install -e .
          git clone https://github.com/randy3k/radian.git
          cd radian
          python -m pip install -e .[test]
          pytest -s --cov=rchitect
      - name: codecov
        run: |
          python -m pip install codecov
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
