name: Test radian

on: [push, pull_request]

env:
  RADIAN_NO_INPUTHOOK: 1

jobs:
  cleanup:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  pytest:
    name: ${{ matrix.os }} r-${{ matrix.r }} py-${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        r: [latest]
        python: [2.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python }}
      - name: Install Microsoft Visual C++
        if: matrix.os == 'windows-latest' && matrix.python == '2.7'
        uses: ilammy/msvc-dev-cmd@v1
      - if: matrix.os == 'windows-latest' && matrix.python == '2.7'
        shell: bash
        run: |
          echo "DISTUTILS_USE_SDK=1" >> $GITHUB_ENV
          echo "MSSdk=1" >> $GITHUB_ENV
      - name: Install setuptools on Python 2.7
        if: matrix.python == '2.7'
        run: python -m pip install setuptools==44.1.1
      - name: Install pywinpty on Windows
        if: matrix.os == 'windows-latest' && matrix.python == '2.7'
        run: python -m pip install pywinpty==0.5.7
      - name: Install rchitect
        run: python -m pip install -e .[test]
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
      - name: Install reticulate
        run: Rscript -e "install.packages('reticulate')"
      - name: Install radian and run tests
        shell: bash
        run: |
          if [ "${{ matrix.python }}" = "2.7" ]; then
            git clone --branch v0.5.12 https://github.com/randy3k/radian
          else
            git clone https://github.com/randy3k/radian
          fi
          cd radian
          python -m pip install -e .[test]
          python -m pip install jedi==0.17.2
          pytest -s
